nameOverride: "loop-frontend"
fullnameOverride: "loop-frontend"

replicaCount: 1

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
    cert-manager.io/cluster-issuer: team-io-kr-letsencrypt-prod
  hosts:
    - host: loop.team.io.kr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: loop-frontend-tls
      hosts:
        - loop.team.io.kr

resources:
  requests:
    memory: 512Mi
    cpu: 100m

image:
  repository: "harbor.homelab.robinjoon.xyz/loop/frontend"
  tag: "20260322-7"

imagePullSecrets:
  - name: "loop-harbor-secret"

readinessProbe:
  httpGet:
    path: "/"
    port: 3000
  initialDelaySeconds: 5

livenessProbe:
  httpGet:
    path: "/"
    port: 3000
  initialDelaySeconds: 10

autoscaling:
  enabled: false

service:
  port: 3000

env:
  - name: VITE_GRAPHQL_ENDPOINT
    value: "https://api.loop.team.io.kr/graphql"

envFrom: []
