nameOverride: "loop-server-docs"
fullnameOverride: "loop-server-docs"

replicaCount: 1

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
    cert-manager.io/cluster-issuer: team-io-kr-letsencrypt-prod
  hosts:
    - host: doc.api.loop.team.io.kr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: loop-server-doc-tls
      hosts:
        - doc.api.loop.team.io.kr

resources:
  requests:
    memory: 1Gi
    cpu: 200m

image:
  repository: "harbor.homelab.robinjoon.xyz/loop/server-docs"
  tag: "20260308-14"

imagePullSecrets:
  - name: "loop-harbor-secret"

ports:
  - containerPort: 80 # 컨테이너 포트 명시
readinessProbe:
  httpGet:
    path: "/"       # 혹은 /health 등 실제 헬스체크 경로
    port: 80    # 앱이 사용하는 실제 포트로 변경
#  initialDelaySeconds: 20 # 앱 구동 시간 고려하여 대기 시간 추가

livenessProbe:
  httpGet:
    path: "/"       # 혹은 /health 등 실제 헬스체크 경로
    port: 80    # 앱이 사용하는 실제 포트로 변경
#  initialDelaySeconds: 20 # 앱 구동 시간 고려하여 대기 시간 추가

autoscaling:
  enabled: false

service:
  port: 80

# Environment variables from Secret
# Secret 생성 방법: backend-secret.yaml 파일 생성 후 적용
#
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-secret
#   namespace: growweek
# type: Opaque
# stringData:
#   SPRING_PROFILES_ACTIVE: "dev"
#   DB_HOST: ""
#   DB_PORT: ""
#   DB_NAME: ""
#   DB_USERNAME: ""
#   DB_PASSWORD: ""
#   JWT_SECRET: ""
#   JWT_EXPIRATION: "3600000"
#   GEMINI_API_KEY: ""
# ---
#
# kubectl apply -f backend-secret.yaml
envFrom: {}

basicAuth:
  enabled: true
  secretName: "server-docs-basic-auth"


